fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    sudo: git://github.com/saz/puppet-sudo.git
    gpg_key: git://github.com/treydock/puppet-gpg_key.git
    zabbix20: git://github.com/treydock/puppet-zabbix20.git
    epel: git://github.com/stahnma/puppet-module-epel.git
    firewall: git://github.com/puppetlabs/puppetlabs-firewall.git
  symlinks:
    fhgfs: "#{source_dir}"
