fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.1.0
    gpg_key:
      repo: git://github.com/treydock/puppet-gpg_key.git
      ref: 0.0.2
  symlinks:
    fhgfs: "#{source_dir}"
