fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.3.1
    gcc:
      repo: https://github.com/puppetlabs/puppetlabs-gcc.git
  symlinks:
    beegfs: "#{source_dir}"
