fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.13.1
    yumrepo_core:
      repo: git://github.com/puppetlabs/puppetlabs-yumrepo_core
      ref: 1.0.1
      puppet_version: ">= 6.0.0"
  symlinks:
    beegfs: "#{source_dir}"
