---
default_set: 'centos-64-x64'
sets:
  'centos-64-x64':
    nodes:
      'main.vm':
        prefab: 'centos-64-x64'
  'centos-59-x64':
    nodes:
      'main.vm':
        prefab: 'centos-59-x64'
  'scientific-64-x64':
    nodes:
      'main.vm':
        prefab: 'scientific-64-x64'
  'scientific-64-x64-multi':
    default_node: 'client'
    nodes:
      'storage':
        prefab: 'scientific-64-x64'
      'client':
        prefab: 'scientific-64-x64'
      'meta-mgmtd':
        prefab: 'scientific-64-x64'
