---
'scientific-64-x64':
  description: ""
  facts:
    kernelrelease: "2.6.32-358.el6.x86_64"
    operatingsystem: Scientific
    kernelmajversion: "2.6"
    architecture: x86_64
    facterversion: "1.7.0"
    kernelversion: "2.6.32"
    operatingsystemrelease: "6.4"
    osfamily: RedHat
    kernel: Linux
    rubyversion: "1.8.7"
  provider_specifics:
    vagrant:
      box: 'scientific-64-x64-vb4210-nocm'
      box_url: 'http://yum.tamu.edu/vagrant/scientific-64-x64-vb4210-nocm.box'