---
dist: xenial
language: ruby
sudo: false
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake release_checks
matrix:
  fast_finish: true
  include:
    - rvm: 2.4.4
      env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes"
    - rvm: 2.5.1
      env: PUPPET_GEM_VERSION="~> 6.0" STRICT_VARIABLES="yes"
    - rvm: 2.4.4
      sudo: required
      services: docker
      env: BEAKER_set="centos-7-x64-docker" BEAKER_PUPPET_COLLECTION=puppet5
      bundler_args:
      before_script: tests/travis-add-beegfs.sh
      script: bundle exec rake beaker
    - rvm: 2.5.1
      sudo: required
      services: docker
      env: BEAKER_set="centos-7-x64-docker" BEAKER_PUPPET_COLLECTION=puppet6
      bundler_args:
      before_script: tests/travis-add-beegfs.sh
      script: bundle exec rake beaker
    - rvm: 2.4.4
      sudo: required
      services: docker
      env: BEAKER_set="centos-6-x64-docker" BEAKER_PUPPET_COLLECTION=puppet5
      bundler_args:
      before_script: tests/travis-add-beegfs.sh
      script: bundle exec rake beaker
    - rvm: 2.5.1
      sudo: required
      services: docker
      env: BEAKER_set="centos-6-x64-docker" BEAKER_PUPPET_COLLECTION=puppet6
      bundler_args:
      before_script: tests/travis-add-beegfs.sh
      script: bundle exec rake beaker

notifications:
  email: false
