name    'treydock-fhgfs'
version '0.0.1'
source 'UNKNOWN'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
