HOSTS:
  centos-7-x64:
    roles:
      - default
      - agent
      - client
      - storage
      - meta
      - mgmt
    platform: el-6-x86_64
    box: centos/7
    hypervisor: vagrant
CONFIG:
  log_level: debug
  type: foss
